//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class server
    {
        public int Info_Id { get; set; }
        public string Server1 { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
    }
}
